defaults:
  - _self_
  - augmentations: asymmetric.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "isoloss-noema-tinyimagenet" # change here for cifar100
method: "directpred"
backbone:
  name: "resnet18"
method_kwargs:
  proj_hidden_dim: 4096
  proj_output_dim: 256
  dp_alpha: 0.5
  dp_normalize: True
  iso: True
  dp_tau: 0.5
  eps_iso: 0.0
  log_eigvals: True
  use_l2: False
momentum:
  base_tau: 0.0
  final_tau: 0.0
data:
  dataset: tinyimagenet
  train_path: "./datasets/tinyimagenet/train"
  val_path: "./datasets/tinyimagenet/val"
  format: "image_folder"
  num_workers: 4
optimizer:
  name: "sgd"
  batch_size: 256
  lr: 0.1
  classifier_lr: 0.1
  weight_decay: 1e-5
  kwargs:
    momentum: 0.9
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 1000
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
